#!/usr/bin/python
# -*-  coding: utf-8 -*-

##
# Current source: https://github.com/open-security/vulnpwn/
##


import sys


sys.dont_write_bytecode = True

from lib.base import base


try:
    fw = base.Base()
    fw.cmdloop()
except KeyboardInterrupt:
    fw.output('')
    fw.output('exit.')
